export const route = {
  // LOGIN: "/",
  // COMPANY_BRANCH_DETAIL: "/company-branch-detail",
  // APP_MENU: "/app_menu",
  // MENU_DASHBOARD: "/menu_dashboard",
  // Module wise route constant list
  // 1: Admission
  // ADMISSION_APLLICATION_FORMS: "/admission/applicationforms",
  // Dashboard
  DASHBOARD: "/dashboard",
  ADMISSION_APLLICATION_FORMS: "/",

  ADMISSION_ADMISSION_STATUS: "/admission/admissionstatus",
  ADMISSION_ELIGIBILITY_CHECK: "/admission/eligibilitycheck",
  ADMISSION_FEE_SUBMISSION: "/admission/feesubmission",
  //Library
  LIBRARY_BORROW_RETURN_BOOKS: "/librarry/borroworreturnbooks",
  LIBRARY_CATALOG_SEARCH: "/librarry/catalogsearch",
  LIBRARY_LIBRARY_TIMING: "/librarry/librarytimings",
  LIBRARY_RESERVATION_SYSTEM: "/librarry/reservationsystem",
  //Administration
  ADMINISTRATION_EVENTS_NOTICES: "/administration/eventsnotices",
  ADMINISTRATION_INFRASTRUCTURE: "/administration/infrastructure",
  ADMINISTRATION_ROLES_PERMISSIONS: "/administration/rolespermissions",
  ADMINISTRATION_STAFF_MANAGEMENT: "/administration/staffmanagement",
  //Timetable
  TIMETABLE_CLASS_SCHEDULES: "/timetable/classschedules",
  TIMETABLE_EXAM_TIMETABLE: "/timetable/examtimetable",
  TIMETABLE_FACULTY_ALLOCATION: "/timetable/facultyallocation",
  TIMETABLE_ROOM_ALLOCATION: "/timetable/roomallocation",
  TIMETABLE_SPECIAL_EVENTS: "/timetable/specialevents",
  //   Student management
  STUDENT_MANAGEMENT_ATTENDANCE: "/student-management/attendance",
  STUDENT_MANAGEMENT_DISCIPLINARY_ACTIONS:
    "/student-management/disciplinaryactions",
  STUDENT_MANAGEMENT_ENROLLMENT: "/student-management/enrollment",
  STUDENT_MANAGEMENT_PARENT_COMMUNICATION:
    "/student-management/parentcommunication",
  STUDENT_MANAGEMENT_PERFORMANCE_TRACKING:
    "/student-management/performancetracking",
  STUDENT_MANAGEMENT_PROFILES: "/student-management/profiles",
  //Finance
  FINANCE_BUDGETING: "/finance/budgeting",
  FINANCE_EXPENSE_TRACKING: "/finance/expensetracking",
  FINANCE_FEE_MANAGEMENT: "/finance/feemanagement",
  FINANCE_FINANCIAL_REPORTS: "/finance/reports",
  //Learning
  LEARNING_ASSIGNMENTS: "/learning/assignments",
  LEARNING_COURSE_MATERIALS: "/learning/coursematerials",
  LEARNING_GRADING: "/learning/grading",
  LEARNING_ONLINE_CLASSES: "/learning/onlineclasses",
  // Exam
  EXAMS_EXAMS_SHEDULE: "/exams/examschedule",
  EXAMS_QUESTIONS_PAPPERS: "/exams/questionpapers",
  EXAMS_RE_EVALUATION: "/exams/reevaluation",
  EXAMS_RESULTS: "/exams/results",
  // Attendance
  ATTENDANCE_ATTENDANCE_REPORTS: "/attendance/attendancereports",
  ATTENDANCE_HOLIDAY_CALENDAR: "/attendance/holidaycalendar",
  ATTENDANCE_LEAVE_REQUESTS: "/attendance/leaverequests",
  ATTENDANCE_STAFF_ATTENDANCE: "/attendance/staffattendance",
  ATTENDANCE_STUDENT_ATTENDANCE: "/attendance/studentattendance",
  // Certifications
  CERTIFICATIONS_CERTIFICATE_REQUESTS: "/certifications/certificaterequests",
  CERTIFICATE_DIGITAL_CERTIFICATIONS: "/certifications/digitalcertifications",
  CERTIFICATIONS_ISSUEING_CERTIFICATES: "/certifications/issuingcertificates",
  CERTIFICATIONS_VERIFICATION: "/certifications/verification",
  // hr management
  HR_MANAGEMENT_EMPLOYEE_RECORDS: "/hr-management/employeerecords",
  HR_MANAGEMENT_LEAVE_MANAGEMENT: "/hr-management/leavemanagement",
  HR_MANAGEMENT_PAYROLL: "/hr-management/payroll",
  HR_MANAGEMENT_RECRUITMENT: "/hr-management/recruitment",
  // Multi Campus
  MULTI_CAMPUS_CAMPUS_MANAGEMENT: "/multi-campus/campusmanagement",
  MULTI_CAMPUS_CAMPUS_REPORTS: "/multi-campus/campusreports",
  MULTI_CAMPUS_INTER_CAMPUS_TRNASFERS: "/multi-campus/intercampustransfers",
  MULTI_CAMPUS_RESOURCE_ALLOCATION: "/multi-campus/resourceallocation",
  // Payroll
  PAYROLL_EMPLOYEE_BENEFITS: "/payroll/employeebenefits",
  PAYROLL_SALARY_PROCESSING: "/payroll/salaryprocessing",
  PAYROLL_SALARY_SLIPS: "/payroll/salaryslips",
  PAYROLL_TAXATION: "/payroll/taxation",
  // User Management
  USERS_LIST: "/users",
  USERS_CREATE: "/users/new",
  USERS_EDIT: "/users/:id/edit",
  USERS_DETAIL: "/users/:id",
  // Student Management
  STUDENT_LIST: "/student-management/profiles",
  STUDENT_CREATE: "/student-management/profiles/new",
  STUDENT_EDIT: "/student-management/profiles/:id/edit",
  STUDENT_DETAIL: "/student-management/profiles/:id",
  STUDENT_ENROLLMENTS: "/student-management/profiles/:id/enrollments",
  STUDENT_RESULTS: "/student-management/profiles/:id/results",
  // Admission Management
  ADMISSION_APPLICATION_LIST: "/admission/applications",
  ADMISSION_APPLICATION_CREATE: "/admission/applications/new",
  ADMISSION_APPLICATION_DETAIL: "/admission/applications/:id",
  // Academic Management
  ACADEMIC_PROGRAM_LIST: "/academic/programs",
  ACADEMIC_PROGRAM_CREATE: "/academic/programs/new",
  ACADEMIC_PROGRAM_EDIT: "/academic/programs/:id/edit",
  ACADEMIC_PROGRAM_DETAIL: "/academic/programs/:id",
  ACADEMIC_COURSE_LIST: "/academic/courses",
  ACADEMIC_COURSE_CREATE: "/academic/courses/new",
  ACADEMIC_COURSE_EDIT: "/academic/courses/:id/edit",
  ACADEMIC_COURSE_DETAIL: "/academic/courses/:id",
  // Timetable Management
  TIMETABLE_LIST: "/timetable/schedules",
  TIMETABLE_CREATE: "/timetable/schedules/new",
  TIMETABLE_EDIT: "/timetable/schedules/:id/edit",
  TIMETABLE_DETAIL: "/timetable/schedules/:id",
  TIMETABLE_ROOMS: "/timetable/rooms",
  // Examination Management
  EXAMINATION_EXAM_LIST: "/examination/exams",
  EXAMINATION_EXAM_CREATE: "/examination/exams/new",
  EXAMINATION_EXAM_EDIT: "/examination/exams/:id/edit",
  EXAMINATION_EXAM_DETAIL: "/examination/exams/:id",
  EXAMINATION_RESULT_LIST: "/examination/results",
  EXAMINATION_RESULT_ENTRY: "/examination/exams/:examId/results",
  // Attendance Management
  ATTENDANCE_RECORD_LIST: "/attendance/records",
  ATTENDANCE_RECORD_CREATE: "/attendance/records/new",
  ATTENDANCE_RECORD_EDIT: "/attendance/records/:id/edit",
  ATTENDANCE_BULK_ENTRY: "/attendance/bulk",
  ATTENDANCE_REPORTS: "/attendance/reports",
  // Finance Management
  FINANCE_FEE_STRUCTURE_LIST: "/finance/fee-structures",
  FINANCE_FEE_STRUCTURE_CREATE: "/finance/fee-structures/new",
  FINANCE_FEE_STRUCTURE_EDIT: "/finance/fee-structures/:id/edit",
  FINANCE_PAYMENT_LIST: "/finance/payments",
  FINANCE_PAYMENT_PROCESS: "/finance/payments/new",
  FINANCE_PAYMENT_DETAIL: "/finance/payments/:id",
  // Learning Management
  LEARNING_MATERIAL_LIST: "/learning/materials",
  LEARNING_MATERIAL_CREATE: "/learning/materials/new",
  LEARNING_MATERIAL_EDIT: "/learning/materials/:id/edit",
  LEARNING_MATERIAL_DETAIL: "/learning/materials/:id",
  LEARNING_ASSIGNMENT_LIST: "/learning/assignments",
  LEARNING_ASSIGNMENT_CREATE: "/learning/assignments/new",
  LEARNING_ASSIGNMENT_EDIT: "/learning/assignments/:id/edit",
  LEARNING_ASSIGNMENT_DETAIL: "/learning/assignments/:id",
  LEARNING_ASSIGNMENT_SUBMISSIONS: "/learning/assignments/:id/submissions",
  LEARNING_SUBMISSION_LIST: "/learning/submissions",
  LEARNING_SUBMISSION_DETAIL: "/learning/submissions/:id",
  LEARNING_SUBMISSION_GRADE: "/learning/submissions/:id/grade",
  // Library Management
  LIBRARY_BOOK_LIST: "/library/books",
  LIBRARY_BOOK_CREATE: "/library/books/new",
  LIBRARY_BOOK_EDIT: "/library/books/:id/edit",
  LIBRARY_BOOK_DETAIL: "/library/books/:id",
  LIBRARY_BORROWING_LIST: "/library/borrowings",
  LIBRARY_BORROWING_CREATE: "/library/borrowings/new",
  LIBRARY_BORROWING_DETAIL: "/library/borrowings/:id",
  LIBRARY_RESERVATION_LIST: "/library/reservations",
  LIBRARY_RESERVATION_DETAIL: "/library/reservations/:id",
  // HR Management
  HR_EMPLOYEE_LIST: "/hr/employees",
  HR_EMPLOYEE_CREATE: "/hr/employees/new",
  HR_EMPLOYEE_EDIT: "/hr/employees/:id/edit",
  HR_EMPLOYEE_DETAIL: "/hr/employees/:id",
  HR_LEAVE_REQUEST_LIST: "/hr/leave-requests",
  HR_LEAVE_REQUEST_CREATE: "/hr/leave-requests/new",
  HR_LEAVE_REQUEST_DETAIL: "/hr/leave-requests/:id",
  HR_JOB_POSTING_LIST: "/hr/job-postings",
  HR_JOB_POSTING_CREATE: "/hr/job-postings/new",
  HR_JOB_POSTING_EDIT: "/hr/job-postings/:id/edit",
  HR_JOB_POSTING_DETAIL: "/hr/job-postings/:id",
  HR_JOB_APPLICATION_LIST: "/hr/job-applications",
  HR_JOB_APPLICATION_DETAIL: "/hr/job-applications/:id",
  // Payroll Management
  PAYROLL_SALARY_STRUCTURE_LIST: "/payroll/salary-structures",
  PAYROLL_SALARY_STRUCTURE_CREATE: "/payroll/salary-structures/new",
  PAYROLL_SALARY_STRUCTURE_EDIT: "/payroll/salary-structures/:id/edit",
  PAYROLL_SALARY_STRUCTURE_DETAIL: "/payroll/salary-structures/:id",
  PAYROLL_PROCESSING_LIST: "/payroll/processings",
  PAYROLL_PROCESSING_CREATE: "/payroll/processings/new",
  PAYROLL_PROCESSING_DETAIL: "/payroll/processings/:id",
  PAYROLL_SUMMARY: "/payroll/summary",
  // Administration
  ADMIN_EVENT_LIST: "/administration/events",
  ADMIN_EVENT_CREATE: "/administration/events/new",
  ADMIN_EVENT_EDIT: "/administration/events/:id/edit",
  ADMIN_EVENT_DETAIL: "/administration/events/:id",
  ADMIN_NOTICE_LIST: "/administration/notices",
  ADMIN_NOTICE_CREATE: "/administration/notices/new",
  ADMIN_NOTICE_EDIT: "/administration/notices/:id/edit",
  ADMIN_NOTICE_DETAIL: "/administration/notices/:id",
  ADMIN_DEPARTMENT_LIST: "/administration/departments",
  ADMIN_DEPARTMENT_CREATE: "/administration/departments/new",
  ADMIN_DEPARTMENT_EDIT: "/administration/departments/:id/edit",
  ADMIN_DEPARTMENT_DETAIL: "/administration/departments/:id",
  ADMIN_SYSTEM_CONFIG: "/administration/system-configs",
  // Certification
  CERTIFICATION_REQUEST_LIST: "/certification/requests",
  CERTIFICATION_REQUEST_CREATE: "/certification/requests/new",
  CERTIFICATION_REQUEST_DETAIL: "/certification/requests/:id",
  CERTIFICATION_CERTIFICATE_LIST: "/certification/certificates",
  CERTIFICATION_CERTIFICATE_DETAIL: "/certification/certificates/:id",
  CERTIFICATION_VERIFY: "/certification/verify",
  // Multi-Campus
  MULTICAMPUS_CAMPUS_LIST: "/multicampus/campuses",
  MULTICAMPUS_CAMPUS_CREATE: "/multicampus/campuses/new",
  MULTICAMPUS_CAMPUS_EDIT: "/multicampus/campuses/:id/edit",
  MULTICAMPUS_CAMPUS_DETAIL: "/multicampus/campuses/:id",
  MULTICAMPUS_CAMPUS_REPORT: "/multicampus/campuses/:id/report",
  MULTICAMPUS_STUDENT_TRANSFER_LIST: "/multicampus/student-transfers",
  MULTICAMPUS_STUDENT_TRANSFER_CREATE: "/multicampus/student-transfers/new",
  MULTICAMPUS_STUDENT_TRANSFER_DETAIL: "/multicampus/student-transfers/:id",
  MULTICAMPUS_STAFF_TRANSFER_LIST: "/multicampus/staff-transfers",
  MULTICAMPUS_STAFF_TRANSFER_CREATE: "/multicampus/staff-transfers/new",
  MULTICAMPUS_STAFF_TRANSFER_DETAIL: "/multicampus/staff-transfers/:id",
};

// public Routes
// export const publicRoutes: RouteObject[] = [
// LOGIN: '/',
// COMPANY_BRANCH_DETAIL: '/company-branch-detail',
// APP_MENU: '/app_menu',
// MENU_DASHBOARD: '/menu_dashboard',
// ];
